esphome:
  name: seeed-esp32s3-sense-01
  friendly_name: Seeed ESP32S3 Sense 01

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "******************************"

ota:
  - platform: esphome
    password: "********************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seeed-Esp32S3-Sense-01"
    password: "***************************"

external_components:
  - source: github://esphome/esphome#5230
    components: [ bme68x_bsec2 ]



i2c:
  sda: 6
  scl: 7
  scan: true

bme68x_bsec2_i2c:
  model: bme688
  address: 0x77
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "BME68x Temperature"
    pressure:
      name: "BME68x Pressure"
    humidity:
      name: "BME68x Humidity"
    iaq:
      name: "BME68x IAQ"
      id: iaq
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"



#  - platform: bme680
#    address: 0x77   # oder 0x76 je nach Modul
#    temperature:
#      name: "BME688 Temperatur"
#    pressure:
#      name: "BME688 Luftdruck"
#    humidity:
#      name: "BME688 Luftfeuchtigkeit"
#    gas_resistance:
#      name: "BME688 Gaswiderstand"
#    update_interval: 10s
